---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx_package_name }}"
    state: installed
    default_release: "{{ nginx_default_release }}"
- name: install php and modules
  apt:
    name: "php{{ nginx_php_version }}-{{ item }}"
    state: installed
  with_items:
    - "{{ nginx_php_dependencies }}"
    - fpm
  when: nginx_install_php_fpm