- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: restart nginx
  systemd: 
    name: restarted
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: reload nginx
  systemd: 
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: start nginx
  systemd: 
    name: nginx
    state: started
    daemon_reload: yes
    enabled: yes

- name: enable nginx
  systemd: 
    name: nginx
    state: stopped
    daemon_reload: yes
    enabled: yes
